version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: app
      POSTGRES_PASSWORD: password
    ports: ["5432:5432"]
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.1.10
    command: ["redpanda","start","--overprovisioned","--smp","1","--reserve-memory","0M","--check=false"]
    ports: ["9092:9092","9644:9644"]
  dynamodb:
    image: amazon/dynamodb-local
    ports: ["8000:8000"]
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: ["9000:9000","9001:9001"]
  

